import { test, expect } from "@playwright/test";
import { clerkIdByEmail } from "../src/clerk.js";
import { signInAs } from "../src/session.js";
import { ROLES } from "../src/data.js";

/** Notifications generated by the earlier journeys, read both sides. */
test.describe("notifications", () => {
  test("B sees invite + approval; badge, read, all-read, deep links persist", async ({ page, baseURL }) => {
    await signInAs(page, baseURL!, await clerkIdByEmail(ROLES.studentB));
    await page.goto("/notifications");
    await expect(page.getByText(/invited/i).first()).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/application.*approved/i).first()).toBeVisible({ timeout: 30_000 });

    // Deep link opens the project destination.
    const first = page.locator('[data-testid^="notification-"]').first();
    const nid = (await first.getAttribute("data-testid"))!.replace("notification-", "");
    await first.getByTestId(`link-notification-${nid}`).click();
    await expect(page).toHaveURL(/projects\/\d+/, { timeout: 20_000 });

    // Mark one read, then all read; unread count clears and persists.
    await page.goto("/notifications");
    const first2 = page.locator('[data-testid^="notification-"]').first();
    const nid2 = (await first2.getAttribute("data-testid"))!.replace("notification-", "");
    await first2.getByTestId(`button-read-${nid2}`).click();
    await page.getByTestId("button-mark-all-read").click();
    await expect(page.getByText(/unread/)).toHaveCount(0, { timeout: 20_000 });
    await page.reload();
    await expect(page.getByText(/unread/)).toHaveCount(0, { timeout: 20_000 });
    await expect(page.locator('[data-testid^="notification-"]').first()).toBeVisible({ timeout: 20_000 });
  });

  test("A does not see B-private notifications", async ({ page, baseURL }) => {
    await signInAs(page, baseURL!, await clerkIdByEmail(ROLES.studentA));
    await page.goto("/notifications");
    await expect(page.getByText("Your application for", { exact: false })).toHaveCount(0);
  });
});
